using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.Web.Mvc.FluentValidation: Mvc Fluent Validation kernel extension for Ninj" +
    "ect")]
[assembly: AssemblyCompanyAttribute("Sean Chambers")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2010 Sean Chambers and contributors")]
[assembly: AssemblyVersionAttribute("2.1.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

